version: 2 # use CircleCI 2.0

defaults: &defaults
  environment: &environment
    CIRCLE_TEST_REPORTS: /tmp/test-results
    CIRCLE_ARTIFACTS: /tmp/test-artifacts
    BUNDLE_JOBS: 4
    BUNDLE_RETRY: 3
    BUNDLE_PATH: ~/spree/vendor/bundle
    COVERAGE: true
  working_directory: ~/spree
  docker:
    - image: &image circleci/ruby:2.5-node-browsers

run_tests: &run_tests
  <<: *defaults
  parallelism: 4
  steps:
    - checkout
    - restore_cache:
        keys:
          - spree-bundle-v3-{{ .Branch }}-{{ checksum ".ruby-version" }}
          - spree-bundle-v3-{{ checksum ".ruby-version" }}
    - run:
        name: Ensure Bundle Install
        command: |
          bundle check --path=~/spree/vendor/bundle || bundle install
          ./build-ci.rb install
    - run:
        name: Install Code Climate Test Reporter
        command: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
    - run:
        name: Run tests
        command: BUNDLE_GEMFILE=../Gemfile ./build-ci.rb test
    - run:
        name: Code Climate Test Coverage
        command: |
          ./cc-test-reporter format-coverage -t simplecov -o "coverage/codeclimate.$CIRCLE_NODE_INDEX.json"
    - store_artifacts:
        path: /tmp/test-artifacts
        destination: test-artifacts
    - store_artifacts:
        path: /tmp/test-results
        destination: raw-test-output
    - store_test_results:
        path: /tmp/test-results
    - deploy:
        command: |
          ./cc-test-reporter sum-coverage --output - --parts $CIRCLE_NODE_TOTAL coverage/codeclimate.*.json | ./cc-test-reporter upload-coverage --debug --input -

jobs:
  bundle_install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - spree-bundle-v3-{{ .Branch }}-{{ checksum ".ruby-version" }}
            - spree-bundle-v3-{{ checksum ".ruby-version" }}
      - run:
          name: Bundle Install
          command: |
            bundle check --path=~/spree/vendor/bundle || bundle install
            ./build-ci.rb install
      - save_cache:
          key: spree-bundle-v3-{{ .Branch }}-{{ checksum ".ruby-version" }}
          paths:
            - ~/spree/vendor/bundle

  run_tests_postgres: &run_tests_postgres
    <<: *run_tests
    environment: &postgres_environment
      <<: *environment
      DB: postgres
      DB_HOST: localhost
      DB_USERNAME: postgres
    docker:
      - image: *image
      - image: circleci/postgres:10-alpine
        environment:
          POSTGRES_USER: postgres

  run_tests_postgres_paperclip:
      <<: *run_tests_postgres
      environment:
        <<: *postgres_environment
        SPREE_USE_PAPERCLIP: true

  run_tests_mysql:
    <<: *run_tests
    environment:
      <<: *environment
      DB: mysql
      DB_HOST: 127.0.0.1
      DB_USERNAME: root
    docker:
      - image: *image
      - image: circleci/mysql:8-ram
        command: [--default-authentication-plugin=mysql_native_password]

workflows:
  version: 2
  main:
    jobs:
      - bundle_install
      - run_tests_postgres:
          requires:
            - bundle_install
      - run_tests_mysql:
          requires:
            - bundle_install
      - run_tests_postgres_paperclip:
          requires:
            - run_tests_postgres
            - bundle_install
